[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hcs-exporter"
version = "0.1.0"
dependencies = [
    "prometheus_client",
    "huaweicloudsdkobs",
    "PyYAML",
    "requests",
]
