image:
  repository: hcs-exporter
  tag: latest
  pullPolicy: IfNotPresent

cronjobs:
  obs:
    enabled: true
    schedule: "*/5 * * * *"
  dcs:
    enabled: true
    schedule: "*/10 * * * *"

config: |
  pushgateway:
    address: "localhost:9091"
    job_name: "hcs-exporter"

  collectors:
    obs:
      rate_limit_sleep: 10
    dcs: {}

env:
  OBS_SERVER: "https://obs.cn-north-4.myhuaweicloud.com"
  IAM_ENDPOINT: ""
  OC_ENDPOINT: ""
  DOMAIN_NAME: ""

# 敏感信息配置（注意：这些值应该在实际部署时通过--set参数或secrets文件提供）
# 不要在版本控制系统中存储真实的敏感信息
secret:
  AccessKeyID: ""
  SecretAccessKey: ""
  USERNAME: ""
  PASSWORD: ""
